server:
  port: 8081

spring:
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true